/*DATAMIGRATION 6CB4CB05-56B3-4CAB-823D-504EB4F26DF7*/ -- Change the script's code only if it needs to be executed again.

-- The following lines are generated by: EXEC Rhetos.HelpDataMigration 'Demo', 'Proba2';
EXEC Rhetos.DataMigrationUse 'Demo', 'Proba2', 'ID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Demo', 'Proba2', 'Naslov', 'nvarchar(256)';
EXEC Rhetos.DataMigrationUse 'Demo', 'Proba2', 'Opis', 'nvarchar(256)';
GO

-- ... write the data migration queries here (don't forget to use the underscore '_' in schema name) ...
UPDATE
	_Demo.Proba2
SET
	Opis = Naslov
WHERE
	Opis is NULL;

EXEC Rhetos.DataMigrationApplyMultiple 'Demo', 'Proba2', 'ID, Opis';